### PR TITLE
brackets necessary for e.g. a && b || c

### PR DESCRIPTION
**Pull request by Yoshi20**

### CODE REVIEW

**Comment by tynx** [comment]
I don't understand as to why this is necessary. Can you please explain?

**Comment by Yoshi20** [comment]
See: http://de.cppreference.com/w/cpp/language/operator_precedence
a && b || c != a && (b || c)

**Comment by tynx** [comment]
ha. nice catch. didn't know that.

But shouldn't be the brackets around the arguments?
like:
(argument1) operator (argument2) ?

**Comment by Yoshi20** [comment]
this seems to do it allready. With my local changes, it looks like this:
while (!(((((oxocard.accelerometer->getCursorX() == 0) && (oxocard.accelerometer->getCursorY() == 7)) || (millis() - msRef >= 5000)))))

To answer your question:
No. This may also be necessary but it doesn't solve:
a && b || c != a && (b || c)
since
(a) && (b) || (c) != (a) && ((b) || (c))

TODO:
- [x] reproduce the problem (see testAccel-Function of the Firmwar-Test) and check compatibility with implementation of google blockly

**Comment by Yoshi20** [comment]
Compile error when using:

```
#include "OXOcardRunner.h"

int msRef;

void user_main() {
  oxocard.matrix->setForeColor(rgb(0, 167, 227));
  oxocard.matrix->fillScreen();
  msRef = millis();
  while (true && false || millis() - msRef < 5000) {
    delay(50);
  }
  // while (!(((true || false) && millis() - msRef >= 5000))) {
  //   delay(50);
  // }
  if (millis() - msRef >= 5000) {
    oxocard.matrix->setForeColor(rgb(51, 204, 0));
  } else {
    oxocard.matrix->setForeColor(rgb(255, 0, 0));
  }
  oxocard.matrix->fillScreen();
  while (1) {
    delay(50);
  }

}
```

See the last commit for a less invasive fix of this problem

**Review by tynx — DISMISSED** [review]

**Review by tynx — APPROVED** [review]

**Pull request merged**
